[PATHS]
journal_file   = D:\python\DN\DNLoggingTool-main\customer_journal_11march25_to_4april25.jrn
stats_csv      = D:\python\DN\DNLoggingTool-main\stats_output.csv
details_csv    = D:\python\DN\DNLoggingTool-main\details_output.csv

[PARSING_KEYS]
;  start_key1 and start_key2 both appear on the Function line e.g:
;  "16:19:44  3217 Function 'VCPPREFS/PR' selected"
;  The transaction type is extracted from this line.
start_key1 = 3217
start_key2 = Function
end_key1   = 3202

[TRANSACTION_MAP]
COUT           = Cash Withdrawal
COUT/GA        = Cash Withdrawal
BAL            = Balance Inquiry
BAL/BI         = Balance Inquiry
BILLPAY        = Bill Payment
CIN            = Cash Deposit
CIN/CI         = Cash Deposit
COUTFAST       = Fast Cash Withdrawal
PINCHG         = Pin Change
PINCHG/CH      = Pin Change
VCPPREFS       = Preferences
VCPPREFS/PR    = Preferences
TRA            = Transfer
AIN            = Account Movement
CHCCDM         = Cheque Deposit
COUT_PRESTAGED = Prestaged Withdrawal
COUTMIXED      = Mixed Withdrawal Notes and Coins
COINOUT        = Coin Withdrawal
COININ         = Coin Deposit
CINMIXED       = Mixed Deposit
MIXEDMEDIA     = Mixed Deposit
CIN_PRESTAGED  = Cardless Deposit
CHQCASH        = Cheque Cashing
PREPAID        = Prepaid Topup
ACCOUNTCHG     = Account Preference
CLEARPREFCHG   = Clear Preference
ENV            = Envelope Deposit
VOUCHER        = Voucher Dispense
FCCHG          = Fast Cash Preference
STP            = Mini Statement
PINUNLOCK      = Pin Unlock